language: java
jdk:
  - openjdk8

install: maven

script:
  - mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - jbustamante@fi.uba.ar
    on_failure: always
