language: java
jdk:
  - openjdk8

install: ant

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ant
      - ant-optional

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - jbustamante@fi.uba.ar
    on_failure: always
